"""Research 公共基础层。"""

from src.research.core.config import (
    OverfittingConfig,
    PredictivePowerConfig,
    ResearchConfig,
    RuleMiningConfig,
    ThresholdSweepConfig,
    load_research_config,
)
from src.research.core.contracts import (
    CandidateDiscoveryResult,
    CandidateEvidence,
    CandidateRuleCondition,
    DataSummary,
    FeatureCandidateDiscoveryResult,
    FeatureCandidateSpec,
    FeatureKind,
    FeaturePromotionReport,
    Finding,
    IndicatorPredictiveResult,
    IndicatorPromotionDecision,
    MiningResult,
    PromotionDecision,
    RobustnessTier,
    RollingICResult,
    StrategyCandidateSpec,
    ThresholdPoint,
    ThresholdSweepResult,
)
from src.research.core.cross_tf import CrossTFAnalysis, CrossTFSignal, analyze_cross_tf
from src.research.core.data_matrix import DataMatrix, build_data_matrix

__all__ = [
    "CandidateDiscoveryResult",
    "CandidateEvidence",
    "CandidateRuleCondition",
    "CrossTFAnalysis",
    "CrossTFSignal",
    "DataMatrix",
    "DataSummary",
    "FeatureCandidateDiscoveryResult",
    "FeatureCandidateSpec",
    "FeatureKind",
    "FeaturePromotionReport",
    "Finding",
    "IndicatorPredictiveResult",
    "IndicatorPromotionDecision",
    "MiningResult",
    "OverfittingConfig",
    "PredictivePowerConfig",
    "PromotionDecision",
    "ResearchConfig",
    "RobustnessTier",
    "RollingICResult",
    "RuleMiningConfig",
    "StrategyCandidateSpec",
    "ThresholdPoint",
    "ThresholdSweepConfig",
    "ThresholdSweepResult",
    "analyze_cross_tf",
    "build_data_matrix",
    "load_research_config",
]
