"""Execution chain reason and category contracts."""

from __future__ import annotations

from ..reasons import REASON_NEW_SIGNAL_OVERRIDE

REASON_CIRCUIT_OPEN = "circuit_open"
REASON_DUPLICATE_SIGNAL_ID = "duplicate_signal_id"
REASON_INVALID_DIRECTION = "invalid_direction"
REASON_PERFORMANCE_PAUSED = "pnl_circuit_paused"
REASON_EQUITY_CURVE_BELOW_MA = "equity_curve_below_ma"
REASON_MARGIN_GUARD_BLOCK = "margin_guard_block"
REASON_QUOTE_STALE = "quote_stale"
REASON_INTRABAR_SYNTHESIS_STALE = "intrabar_synthesis_stale"
REASON_INTRABAR_SYNTHESIS_UNAVAILABLE = "intrabar_synthesis_unavailable"
REASON_MIN_CONFIDENCE = "min_confidence"
REASON_EOD_BLOCK = "after_eod_block"
REASON_LIMIT_REACHED = "max_concurrent_positions_per_symbol"
REASON_REENTRY_COOLDOWN = "reentry_cooldown"
REASON_SPREAD_TO_STOP_RATIO_TOO_HIGH = "spread_to_stop_ratio_too_high"
REASON_TRADE_PARAMS_UNAVAILABLE = "trade_params_unavailable"
REASON_DUPLICATE_POSITION_SAME_STRATEGY = "position_same_strategy_direction"
REASON_DUPLICATE_PENDING_SAME_STRATEGY = "pending_entry_same_strategy_direction"
REASON_MISSING_SIGNAL_ID = "missing_signal_id"
REASON_ORDER_ORDERS_LOOKUP_FAILED = "orders_lookup_failed"
REASON_ORDER_POSITIONS_LOOKUP_FAILED = "positions_lookup_failed"
REASON_ORDER_MISSING_WITHOUT_POSITION = "order_missing_without_position"
REASON_PENDING_ORDER_FAILED = "pending_order_failed"
REASON_INTRABAR_GUARD_MISSING = "intrabar_guard_missing"
REASON_INTRABAR_PARENT_BAR_MISSING = "missing_parent_bar_time"
REASON_INTRABAR_GUARD_BLOCKED = "intrabar_guard_blocked"
REASON_INTRABAR_GATE_BLOCKED = "intrabar_gate_blocked"
REASON_EXECUTION_GATE_BLOCKED = "execution_gate_blocked"
REASON_QUEUE_OVERFLOW = "queue_overflow"
REASON_HTF_CONFLICT_BLOCK = "htf_conflict_block"
REASON_AUTO_TRADE_DISABLED = "auto_trade_disabled"
REASON_INTRABAR_POSITION_ALREADY_VALIDATED = "intrabar_position_already_validated"
REASON_INTRABAR_POSITION_HOLD = "intrabar_position_hold"
REASON_INTRABAR_TRADING_DISABLED = "intrabar_trading_disabled"
REASON_STRATEGY_NOT_INTRABAR_ENABLED = "strategy_not_intrabar_enabled"
REASON_STRATEGY_CANDIDATE_ONLY = "strategy_candidate_only"
REASON_STRATEGY_DEMO_VALIDATION = "strategy_demo_validation"
REASON_STRATEGY_MAX_LIVE_POSITIONS = "strategy_max_live_positions"
REASON_STRATEGY_REQUIRES_PENDING_ENTRY = "strategy_requires_pending_entry"
REASON_STRATEGY_LOCKED_TIMEFRAME = "strategy_locked_timeframe"
REASON_STRATEGY_LOCKED_SESSION = "strategy_locked_session"
REASON_SINGLE_TRADE_LOSS_CAP = "single_trade_loss_cap_exceeded"


SKIP_CATEGORY_CONFIDENCE = "confidence"
SKIP_CATEGORY_POSITION = "position"
SKIP_CATEGORY_CIRCUIT = "circuit"
SKIP_CATEGORY_RISK_GUARD = "risk_guard"
SKIP_CATEGORY_HTF_ALIGNMENT = "htf_alignment"
SKIP_CATEGORY_EOD_GUARD = "eod_guard"
SKIP_CATEGORY_COOLDOWN = "cooldown"
SKIP_CATEGORY_COST_GUARD = "cost_guard"
SKIP_CATEGORY_TRADE_PARAMS = "trade_params"
SKIP_CATEGORY_GOVERNANCE = "governance"
SKIP_CATEGORY_DUPLICATE_GUARD = "duplicate_guard"
SKIP_CATEGORY_EXECUTION_GATE = "execution_gate"
SKIP_CATEGORY_PERFORMANCE = "performance"
SKIP_CATEGORY_EQUITY_FILTER = "equity_filter"
SKIP_CATEGORY_EXECUTION_INPUT = "execution_input"
SKIP_CATEGORY_MARKET_DATA = "market_data"
SKIP_CATEGORY_PENDING_SUBMIT = "pending_submit"
SKIP_CATEGORY_RISK_SERVICE = "risk_service"
SKIP_CATEGORY_DISPATCH = "dispatch"
SKIP_CATEGORY_OTHER = "other"


_EXACT_CATEGORY_MAP: dict[str, str] = {
    REASON_MIN_CONFIDENCE: SKIP_CATEGORY_CONFIDENCE,
    REASON_LIMIT_REACHED: SKIP_CATEGORY_POSITION,
    REASON_PERFORMANCE_PAUSED: SKIP_CATEGORY_CIRCUIT,
    REASON_MARGIN_GUARD_BLOCK: SKIP_CATEGORY_RISK_GUARD,
    REASON_QUOTE_STALE: SKIP_CATEGORY_MARKET_DATA,
    REASON_INTRABAR_SYNTHESIS_STALE: SKIP_CATEGORY_MARKET_DATA,
    REASON_INTRABAR_SYNTHESIS_UNAVAILABLE: SKIP_CATEGORY_MARKET_DATA,
    REASON_HTF_CONFLICT_BLOCK: SKIP_CATEGORY_HTF_ALIGNMENT,
    REASON_EOD_BLOCK: SKIP_CATEGORY_EOD_GUARD,
    REASON_REENTRY_COOLDOWN: SKIP_CATEGORY_COOLDOWN,
    REASON_SPREAD_TO_STOP_RATIO_TOO_HIGH: SKIP_CATEGORY_COST_GUARD,
    REASON_SINGLE_TRADE_LOSS_CAP: SKIP_CATEGORY_RISK_GUARD,
    REASON_TRADE_PARAMS_UNAVAILABLE: SKIP_CATEGORY_TRADE_PARAMS,
    REASON_DUPLICATE_SIGNAL_ID: SKIP_CATEGORY_DUPLICATE_GUARD,
    REASON_DUPLICATE_POSITION_SAME_STRATEGY: SKIP_CATEGORY_DUPLICATE_GUARD,
    REASON_DUPLICATE_PENDING_SAME_STRATEGY: SKIP_CATEGORY_DUPLICATE_GUARD,
    REASON_PERFORMANCE_PAUSED: SKIP_CATEGORY_CIRCUIT,
    REASON_EQUITY_CURVE_BELOW_MA: SKIP_CATEGORY_EQUITY_FILTER,
    REASON_MISSING_SIGNAL_ID: SKIP_CATEGORY_EXECUTION_INPUT,
    REASON_NEW_SIGNAL_OVERRIDE: SKIP_CATEGORY_EXECUTION_INPUT,
    REASON_PENDING_ORDER_FAILED: SKIP_CATEGORY_PENDING_SUBMIT,
    REASON_QUEUE_OVERFLOW: SKIP_CATEGORY_OTHER,
    REASON_AUTO_TRADE_DISABLED: SKIP_CATEGORY_EXECUTION_GATE,
    REASON_INTRABAR_POSITION_ALREADY_VALIDATED: SKIP_CATEGORY_POSITION,
    REASON_INTRABAR_POSITION_HOLD: SKIP_CATEGORY_POSITION,
    REASON_INTRABAR_TRADING_DISABLED: SKIP_CATEGORY_EXECUTION_GATE,
    REASON_STRATEGY_NOT_INTRABAR_ENABLED: SKIP_CATEGORY_EXECUTION_GATE,
    REASON_STRATEGY_CANDIDATE_ONLY: SKIP_CATEGORY_GOVERNANCE,
    REASON_STRATEGY_DEMO_VALIDATION: SKIP_CATEGORY_GOVERNANCE,
    REASON_STRATEGY_LOCKED_TIMEFRAME: SKIP_CATEGORY_GOVERNANCE,
    REASON_STRATEGY_LOCKED_SESSION: SKIP_CATEGORY_GOVERNANCE,
    REASON_STRATEGY_MAX_LIVE_POSITIONS: SKIP_CATEGORY_POSITION,
    REASON_STRATEGY_REQUIRES_PENDING_ENTRY: SKIP_CATEGORY_EXECUTION_GATE,
}


_PREFIX_CATEGORY_PATTERNS: list[tuple[str, str]] = [
    ("duplicate", SKIP_CATEGORY_DUPLICATE_GUARD),
    ("same_strategy", SKIP_CATEGORY_DUPLICATE_GUARD),
    ("execution_gate", SKIP_CATEGORY_EXECUTION_GATE),
    ("gate", SKIP_CATEGORY_EXECUTION_GATE),
    ("armed", SKIP_CATEGORY_EXECUTION_GATE),
]


def reason_category(reason: str) -> str:
    if not reason:
        return SKIP_CATEGORY_OTHER

    if reason in _EXACT_CATEGORY_MAP:
        return _EXACT_CATEGORY_MAP[reason]

    if reason.startswith(f"{REASON_PENDING_ORDER_FAILED}:"):
        return SKIP_CATEGORY_PENDING_SUBMIT

    for key, category in _PREFIX_CATEGORY_PATTERNS:
        if key in reason:
            return category

    if reason == REASON_CIRCUIT_OPEN:
        return SKIP_CATEGORY_CIRCUIT

    return SKIP_CATEGORY_OTHER


__all__ = [
    "REASON_CIRCUIT_OPEN",
    "REASON_DUPLICATE_SIGNAL_ID",
    "REASON_INVALID_DIRECTION",
    "REASON_PERFORMANCE_PAUSED",
    "REASON_EQUITY_CURVE_BELOW_MA",
    "REASON_MARGIN_GUARD_BLOCK",
    "REASON_QUOTE_STALE",
    "REASON_INTRABAR_SYNTHESIS_STALE",
    "REASON_INTRABAR_SYNTHESIS_UNAVAILABLE",
    "REASON_MIN_CONFIDENCE",
    "REASON_EOD_BLOCK",
    "REASON_LIMIT_REACHED",
    "REASON_REENTRY_COOLDOWN",
    "REASON_SPREAD_TO_STOP_RATIO_TOO_HIGH",
    "REASON_TRADE_PARAMS_UNAVAILABLE",
    "REASON_DUPLICATE_POSITION_SAME_STRATEGY",
    "REASON_DUPLICATE_PENDING_SAME_STRATEGY",
    "REASON_MISSING_SIGNAL_ID",
    "REASON_NEW_SIGNAL_OVERRIDE",
    "REASON_ORDER_ORDERS_LOOKUP_FAILED",
    "REASON_ORDER_POSITIONS_LOOKUP_FAILED",
    "REASON_ORDER_MISSING_WITHOUT_POSITION",
    "REASON_PENDING_ORDER_FAILED",
    "REASON_INTRABAR_GUARD_MISSING",
    "REASON_INTRABAR_PARENT_BAR_MISSING",
    "REASON_INTRABAR_GUARD_BLOCKED",
    "REASON_INTRABAR_GATE_BLOCKED",
    "REASON_EXECUTION_GATE_BLOCKED",
    "REASON_QUEUE_OVERFLOW",
    "REASON_INTRABAR_TRADING_DISABLED",
    "REASON_AUTO_TRADE_DISABLED",
    "REASON_INTRABAR_POSITION_ALREADY_VALIDATED",
    "REASON_INTRABAR_POSITION_HOLD",
    "REASON_STRATEGY_NOT_INTRABAR_ENABLED",
    "REASON_STRATEGY_CANDIDATE_ONLY",
    "REASON_STRATEGY_DEMO_VALIDATION",
    "REASON_STRATEGY_LOCKED_TIMEFRAME",
    "REASON_STRATEGY_LOCKED_SESSION",
    "REASON_STRATEGY_MAX_LIVE_POSITIONS",
    "REASON_STRATEGY_REQUIRES_PENDING_ENTRY",
    "REASON_HTF_CONFLICT_BLOCK",
    "SKIP_CATEGORY_CONFIDENCE",
    "SKIP_CATEGORY_POSITION",
    "SKIP_CATEGORY_CIRCUIT",
    "SKIP_CATEGORY_RISK_GUARD",
    "SKIP_CATEGORY_HTF_ALIGNMENT",
    "SKIP_CATEGORY_EOD_GUARD",
    "SKIP_CATEGORY_COOLDOWN",
    "SKIP_CATEGORY_COST_GUARD",
    "SKIP_CATEGORY_TRADE_PARAMS",
    "SKIP_CATEGORY_GOVERNANCE",
    "SKIP_CATEGORY_DUPLICATE_GUARD",
    "SKIP_CATEGORY_EXECUTION_GATE",
    "SKIP_CATEGORY_PERFORMANCE",
    "SKIP_CATEGORY_EQUITY_FILTER",
    "SKIP_CATEGORY_EXECUTION_INPUT",
    "SKIP_CATEGORY_MARKET_DATA",
    "SKIP_CATEGORY_PENDING_SUBMIT",
    "SKIP_CATEGORY_RISK_SERVICE",
    "SKIP_CATEGORY_DISPATCH",
    "SKIP_CATEGORY_OTHER",
    "reason_category",
]
