from __future__ import annotations


SESSION_BUCKET_ASIA = "asia"
SESSION_BUCKET_EUROPE = "europe"
SESSION_BUCKET_US = "us"
SESSION_BUCKET_OFF_HOURS = "off_hours"
SESSION_BUCKET_ALL_DAY = "all_day"
SESSION_BUCKET_ASIA_EUROPE_OVERLAP = "asia_europe_overlap"
SESSION_BUCKET_EUROPE_US_OVERLAP = "europe_us_overlap"

ECONOMIC_SESSION_BUCKETS: tuple[str, ...] = (
    SESSION_BUCKET_ASIA,
    SESSION_BUCKET_EUROPE,
    SESSION_BUCKET_US,
    SESSION_BUCKET_OFF_HOURS,
    SESSION_BUCKET_ALL_DAY,
    SESSION_BUCKET_ASIA_EUROPE_OVERLAP,
    SESSION_BUCKET_EUROPE_US_OVERLAP,
)

EVENT_STATUS_SCHEDULED = "scheduled"
EVENT_STATUS_IMMINENT = "imminent"
EVENT_STATUS_PENDING_RELEASE = "pending_release"
EVENT_STATUS_RELEASED = "released"
EVENT_STATUS_CANCELLED = "cancelled"
EVENT_STATUS_DELETED = "deleted"

ECONOMIC_EVENT_STATUSES: tuple[str, ...] = (
    EVENT_STATUS_SCHEDULED,
    EVENT_STATUS_IMMINENT,
    EVENT_STATUS_PENDING_RELEASE,
    EVENT_STATUS_RELEASED,
    EVENT_STATUS_CANCELLED,
    EVENT_STATUS_DELETED,
)

UPCOMING_EVENT_STATUSES: tuple[str, ...] = (
    EVENT_STATUS_SCHEDULED,
    EVENT_STATUS_IMMINENT,
    EVENT_STATUS_PENDING_RELEASE,
)

SESSION_BUCKET_CHECK_CONSTRAINT = "economic_calendar_events_session_bucket_check"
EVENT_STATUS_CHECK_CONSTRAINT = "economic_calendar_events_status_check"


def sql_string_literals(values: tuple[str, ...]) -> str:
    return ", ".join(f"'{value}'" for value in values)


__all__ = [
    "ECONOMIC_EVENT_STATUSES",
    "ECONOMIC_SESSION_BUCKETS",
    "EVENT_STATUS_CHECK_CONSTRAINT",
    "EVENT_STATUS_CANCELLED",
    "EVENT_STATUS_DELETED",
    "EVENT_STATUS_IMMINENT",
    "EVENT_STATUS_PENDING_RELEASE",
    "EVENT_STATUS_RELEASED",
    "EVENT_STATUS_SCHEDULED",
    "SESSION_BUCKET_ALL_DAY",
    "SESSION_BUCKET_ASIA",
    "SESSION_BUCKET_ASIA_EUROPE_OVERLAP",
    "SESSION_BUCKET_CHECK_CONSTRAINT",
    "SESSION_BUCKET_EUROPE",
    "SESSION_BUCKET_EUROPE_US_OVERLAP",
    "SESSION_BUCKET_OFF_HOURS",
    "SESSION_BUCKET_US",
    "UPCOMING_EVENT_STATUSES",
    "sql_string_literals",
]
