"""
Configuration package public entrypoint.
"""

from __future__ import annotations

from src.config.centralized import (
    APIConfig,
    EconomicConfig,
    IngestConfig,
    IntervalConfig,
    LimitConfig,
    RiskConfig,
    SignalConfig,
    SystemConfig,
    TradingConfig,
    TradingOpsConfig,
    get_api_config,
    get_config_provenance_snapshot,
    get_economic_config,
    get_effective_config_snapshot,
    get_ingest_config,
    get_interval_config,
    get_limit_config,
    get_risk_config,
    get_runtime_data_path,
    get_shared_default_symbol,
    get_shared_symbols,
    get_shared_timeframes,
    get_signal_config,
    get_system_config,
    get_trading_config,
    get_trading_ops_config,
    reload_configs,
    validate_config_consistency,
)
from src.config.database import DBSettings, load_db_settings
from src.config.indicator_config import (
    CacheStrategy,
    ComputeMode,
    ConfigLoader as IndicatorConfigLoader,
    ConfigManager as IndicatorConfigManager,
    IndicatorConfig,
    PipelineConfig as IndicatorPipelineConfig,
    UnifiedIndicatorConfig,
    get_config as get_indicator_config,
    get_global_config_manager as get_indicator_config_manager,
    normalize_indicator_func_path,
)
from src.config.indicator_runtime import (
    IndicatorSettings,
    load_indicator_settings,
    load_indicator_tasks,
)
from src.config.instance_context import (
    get_current_environment,
    get_current_instance_name,
    normalize_environment,
    resolve_instance_config_dir,
    set_current_environment,
    set_current_instance_name,
)
from src.config.mt5 import MT5Settings, load_group_mt5_settings, load_mt5_settings
from src.config.runtime_identity import (
    RuntimeIdentity,
    build_account_key,
    get_runtime_identity,
    list_mt5_accounts,
    validate_mt5_topology,
)
from src.config.topology import (
    TopologyAssignment,
    TopologyGroup,
    find_topology_group_for_instance,
    iter_group_instances,
    load_topology_group,
    load_topology_groups,
    resolve_current_environment,
    resolve_topology_assignment,
)
from src.config.runtime import (
    IngestSettings,
    MarketSettings,
    get_runtime_ingest_settings,
    get_runtime_market_settings,
)
from src.config.storage import StorageSettings, load_storage_settings
from src.config.utils import (
    ConfigValidator,
    get_merged_config,
    get_merged_option_source,
    load_config_with_base,
    load_ini_config,
    resolve_config_path,
)

__all__ = [
    "APIConfig",
    "CacheStrategy",
    "ComputeMode",
    "ConfigValidator",
    "DBSettings",
    "EconomicConfig",
    "IndicatorConfig",
    "IndicatorConfigLoader",
    "IndicatorConfigManager",
    "IndicatorPipelineConfig",
    "IndicatorSettings",
    "IngestConfig",
    "IngestSettings",
    "IntervalConfig",
    "LimitConfig",
    "MT5Settings",
    "MarketSettings",
    "RiskConfig",
    "RuntimeIdentity",
    "SignalConfig",
    "StorageSettings",
    "SystemConfig",
    "TradingConfig",
    "TradingOpsConfig",
    "UnifiedIndicatorConfig",
    "build_account_key",
    "get_api_config",
    "get_config_provenance_snapshot",
    "get_economic_config",
    "get_effective_config_snapshot",
    "get_indicator_config",
    "get_indicator_config_manager",
    "get_ingest_config",
    "get_interval_config",
    "get_limit_config",
    "get_current_instance_name",
    "get_current_environment",
    "get_merged_config",
    "get_merged_option_source",
    "get_risk_config",
    "get_runtime_identity",
    "get_runtime_data_path",
    "get_runtime_ingest_settings",
    "get_runtime_market_settings",
    "get_shared_default_symbol",
    "get_shared_symbols",
    "get_shared_timeframes",
    "get_signal_config",
    "get_system_config",
    "get_trading_config",
    "get_trading_ops_config",
    "find_topology_group_for_instance",
    "iter_group_instances",
    "list_mt5_accounts",
    "load_config_with_base",
    "load_db_settings",
    "load_group_mt5_settings",
    "load_indicator_settings",
    "load_indicator_tasks",
    "load_ini_config",
    "load_mt5_settings",
    "load_topology_group",
    "load_topology_groups",
    "load_storage_settings",
    "normalize_environment",
    "normalize_indicator_func_path",
    "reload_configs",
    "resolve_current_environment",
    "resolve_instance_config_dir",
    "resolve_config_path",
    "resolve_topology_assignment",
    "set_current_environment",
    "set_current_instance_name",
    "TopologyAssignment",
    "TopologyGroup",
    "validate_config_consistency",
    "validate_mt5_topology",
]
