"""
Timescale schema and SQL statements grouped by module.
"""

from .ticks import DDL as TICKS_DDL, INSERT_SQL as INSERT_TICKS_SQL
from .quotes import DDL as QUOTES_DDL, INSERT_SQL as INSERT_QUOTES_SQL
from .ohlc import (
    DDL as OHLC_DDL,
    INSERT_SQL as INSERT_OHLC_SQL,
    UPSERT_SQL as UPSERT_OHLC_SQL,
)
from .intrabar import DDL as INTRABAR_DDL, INSERT_SQL as INSERT_INTRABAR_SQL
from .economic_calendar import (
    DDL as ECONOMIC_CALENDAR_DDL,
    DELETE_BY_KEYS_SQL as DELETE_ECONOMIC_CALENDAR_BY_KEYS_SQL,
    INSERT_UPDATE_SQL as INSERT_ECONOMIC_CALENDAR_UPDATE_SQL,
    UPSERT_SQL as UPSERT_ECONOMIC_CALENDAR_SQL,
)
from .runtime_tasks import DDL as RUNTIME_TASKS_DDL, UPSERT_SQL as UPSERT_RUNTIME_TASK_STATUS_SQL
from .trade_command_audits import (
    DDL as TRADE_COMMAND_AUDITS_DDL,
    INSERT_SQL as INSERT_TRADE_COMMAND_AUDITS_SQL,
)
from .pipeline_trace_events import (
    DDL as PIPELINE_TRACE_EVENTS_DDL,
    INSERT_SQL as INSERT_PIPELINE_TRACE_EVENTS_SQL,
)
from .pending_order_states import DDL as PENDING_ORDER_STATES_DDL, UPSERT_SQL as UPSERT_PENDING_ORDER_STATES_SQL
from .position_runtime_states import DDL as POSITION_RUNTIME_STATES_DDL, UPSERT_SQL as UPSERT_POSITION_RUNTIME_STATES_SQL
from .trade_control_state import DDL as TRADE_CONTROL_STATE_DDL, UPSERT_SQL as UPSERT_TRADE_CONTROL_STATE_SQL
from .signals import (
    DDL as SIGNAL_EVENTS_DDL,
    INSERT_SQL as INSERT_SIGNAL_EVENTS_SQL,
    PREVIEW_INSERT_SQL as INSERT_SIGNAL_PREVIEW_EVENTS_SQL,
)
from .signal_outcomes import (
    DDL as SIGNAL_OUTCOMES_DDL,
    EXPECTANCY_SQL as SIGNAL_OUTCOMES_EXPECTANCY_SQL,
    INSERT_SQL as INSERT_SIGNAL_OUTCOMES_SQL,
    WINRATE_SQL as SIGNAL_OUTCOMES_WINRATE_SQL,
)
from .auto_executions import DDL as AUTO_EXECUTIONS_DDL, INSERT_SQL as INSERT_AUTO_EXECUTIONS_SQL
from .trade_outcomes import DDL as TRADE_OUTCOMES_DDL, INSERT_SQL as INSERT_TRADE_OUTCOMES_SQL
from .market_impact import (
    DDL as MARKET_IMPACT_DDL,
    UPSERT_SQL as UPSERT_MARKET_IMPACT_SQL,
    FETCH_BY_EVENT_SQL as FETCH_MARKET_IMPACT_BY_EVENT_SQL,
    AGGREGATED_STATS_SQL as MARKET_IMPACT_AGGREGATED_STATS_SQL,
)
from .backtest import (
    DDL as BACKTEST_DDL,
    INSERT_RUN_SQL as INSERT_BACKTEST_RUN_SQL,
    INSERT_TRADE_SQL as INSERT_BACKTEST_TRADE_SQL,
)
from .position_sl_tp_history import (
    DDL as POSITION_SL_TP_HISTORY_DDL,
    INSERT_SQL as INSERT_POSITION_SL_TP_HISTORY_SQL,
)

DDL_STATEMENTS = [
    TICKS_DDL,
    QUOTES_DDL,
    OHLC_DDL,
    INTRABAR_DDL,
    ECONOMIC_CALENDAR_DDL,
    RUNTIME_TASKS_DDL,
    TRADE_COMMAND_AUDITS_DDL,
    PIPELINE_TRACE_EVENTS_DDL,
    PENDING_ORDER_STATES_DDL,
    POSITION_RUNTIME_STATES_DDL,
    TRADE_CONTROL_STATE_DDL,
    SIGNAL_EVENTS_DDL,
    SIGNAL_OUTCOMES_DDL,
    AUTO_EXECUTIONS_DDL,
    TRADE_OUTCOMES_DDL,
    MARKET_IMPACT_DDL,
    BACKTEST_DDL,
    POSITION_SL_TP_HISTORY_DDL,
]

__all__ = [
    "DDL_STATEMENTS",
    "INSERT_TICKS_SQL",
    "INSERT_QUOTES_SQL",
    "INSERT_OHLC_SQL",
    "UPSERT_OHLC_SQL",
    "INSERT_INTRABAR_SQL",
    "UPSERT_ECONOMIC_CALENDAR_SQL",
    "INSERT_ECONOMIC_CALENDAR_UPDATE_SQL",
    "DELETE_ECONOMIC_CALENDAR_BY_KEYS_SQL",
    "UPSERT_RUNTIME_TASK_STATUS_SQL",
    "INSERT_TRADE_COMMAND_AUDITS_SQL",
    "INSERT_PIPELINE_TRACE_EVENTS_SQL",
    "UPSERT_PENDING_ORDER_STATES_SQL",
    "UPSERT_POSITION_RUNTIME_STATES_SQL",
    "UPSERT_TRADE_CONTROL_STATE_SQL",
    "INSERT_SIGNAL_EVENTS_SQL",
    "INSERT_SIGNAL_PREVIEW_EVENTS_SQL",
    "INSERT_SIGNAL_OUTCOMES_SQL",
    "SIGNAL_OUTCOMES_EXPECTANCY_SQL",
    "SIGNAL_OUTCOMES_WINRATE_SQL",
    "INSERT_AUTO_EXECUTIONS_SQL",
    "INSERT_TRADE_OUTCOMES_SQL",
    "UPSERT_MARKET_IMPACT_SQL",
    "FETCH_MARKET_IMPACT_BY_EVENT_SQL",
    "MARKET_IMPACT_AGGREGATED_STATS_SQL",
]
