"""
Timescale schema and SQL statements grouped by module.
"""

from .ticks import DDL as TICKS_DDL, INSERT_SQL as INSERT_TICKS_SQL
from .quotes import DDL as QUOTES_DDL, INSERT_SQL as INSERT_QUOTES_SQL
from .ohlc import (
    DDL as OHLC_DDL,
    INSERT_SQL as INSERT_OHLC_SQL,
    UPSERT_SQL as UPSERT_OHLC_SQL,
)
from .intrabar import DDL as INTRABAR_DDL, INSERT_SQL as INSERT_INTRABAR_SQL
from .economic_calendar import (
    DDL as ECONOMIC_CALENDAR_DDL,
    DELETE_BY_KEYS_SQL as DELETE_ECONOMIC_CALENDAR_BY_KEYS_SQL,
    INSERT_UPDATE_SQL as INSERT_ECONOMIC_CALENDAR_UPDATE_SQL,
    UPSERT_SQL as UPSERT_ECONOMIC_CALENDAR_SQL,
)
from .runtime_tasks import DDL as RUNTIME_TASKS_DDL, UPSERT_SQL as UPSERT_RUNTIME_TASK_STATUS_SQL

DDL_STATEMENTS = [
    TICKS_DDL,
    QUOTES_DDL,
    OHLC_DDL,
    INTRABAR_DDL,
    ECONOMIC_CALENDAR_DDL,
    RUNTIME_TASKS_DDL,
]

__all__ = [
    "DDL_STATEMENTS",
    "INSERT_TICKS_SQL",
    "INSERT_QUOTES_SQL",
    "INSERT_OHLC_SQL",
    "UPSERT_OHLC_SQL",
    "INSERT_INTRABAR_SQL",
    "UPSERT_ECONOMIC_CALENDAR_SQL",
    "INSERT_ECONOMIC_CALENDAR_UPDATE_SQL",
    "DELETE_ECONOMIC_CALENDAR_BY_KEYS_SQL",
    "UPSERT_RUNTIME_TASK_STATUS_SQL",
]
